### ISSUE TITLE
Comparison to other communication libraries

### ISSUE THREAD

**Issue by weberdaniel** [entc/cape#1]
Dear ladies and gentlemen,

What is the Userbase of the QORE/QBus libraries?

What is the advantage of QORE/QBus in comparison to communication middleware such as

    C++ Actor Framework (github.com/actor-framework)
    POCO ( https://pocoproject.org/ )
    ACE (https://www.dre.vanderbilt.edu/~schmidt/ACE.html )

Is this a valid communication library for an operational setup or is it an experimental library?

Kind regards,
Daniel Weber

**Comment by entc** [comment]
Hello Daniel,

thanks for your interest, but the cape library does not address to be a communication library nor to be a C++ framework. The goal of cape is to solve common issues a C software developer has probably faced in his work life. The library is a wrapper for functions or function entities which will be provided by operating systems and also provides additional classes for basic data containers, safe string handling, serialization, queues, .... 

You probably reference to the part which covers asyncronous IO:
The library wrappes different approaches for each platform using the most efficient technologies to handle IO in the OS.
All modern OS already providing schedulers, IO 'handlers', ... to operate at a maxium level. Those handlers are used internally but they are also available by the OS interface. Instead of using another middleware, why not using a direct approach? The application which is using this approach just need to react on events, which covers enough for a modern event driven software. Using C instead of C++ also reduces the footprint to make this library very lightweight and easy to integrade into other frameworks.

This library is in a productive state, and was developed and enhanced over several years.

Cheers

**Comment by weberdaniel** [comment]
Hi entc,

is there a documentation of the library somehwere available or a good tutorial on where to get started and have a more detailed look?

Kind regards,
Daniel

**Comment by entc** [comment]
Hi Daniel,

this repo is not used anymore. Please checkout qbus_collection under entc

I will add a short description how to start.


Cheers

**Comment by weberdaniel** [comment]
Ok, since it is no longer used -> i will close it.
